### ISSUE TITLE
Retrieve all users

### ISSUE THREAD

**Issue by vhugogarcia** [f-miyu/Plugin.FirebaseAuth#21]
Thanks for this great plugin! I am wondering if it is possible to retrieve all users using the plugin. 

Thanks in advance

**Comment by actopozipc** [comment]
I highly doubt that this is possible, whats the use case?

**Comment by actopozipc** [comment]
This doesn't sound effective since you would have to fetch the data of all users to get a single integer-value. Imagine having a big database with a few thousand or even more entrys.  
I would recommend you to make a seperate realtime-database with an count-entry that gets refreshed/edited with every registration.

**Comment by vhugogarcia** [comment]
Thanks @actopozipc . I implemented that approach and it worked very good. Thanks for the recommendation. :)
